-- oracle/schema.sql
--
-- Logistics Event Processing
-- GPS-first Oracle schema.
--
-- The database stores successfully normalised GPS telemetry only.
-- Raw and failed events are handled through structured Python logging.
SET SERVEROUTPUT ON;
PROMPT Creating logistics GPS schema...
--------------------------------------------------------------------------------
-- Drop existing tables
--------------------------------------------------------------------------------
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE gps PURGE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE vehicles PURGE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE drivers PURGE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/
--------------------------------------------------------------------------------
-- drivers
--------------------------------------------------------------------------------
CREATE TABLE drivers (
  driver_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY
            CONSTRAINT pk_drivers PRIMARY KEY,
  driver_code VARCHAR2(50) NOT NULL,
  driver_name VARCHAR2(100) NOT NULL,
  active_flag CHAR(1) DEFAULT 'Y' NOT NULL,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT uq_drivers_driver_code
    UNIQUE (driver_code),
  CONSTRAINT ck_drivers_active_flag
    CHECK (active_flag IN ('Y', 'N'))
);
--------------------------------------------------------------------------------
-- vehicles
--------------------------------------------------------------------------------
CREATE TABLE vehicles (
  vehicle_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY
             CONSTRAINT pk_vehicles PRIMARY KEY,
  vehicle_code VARCHAR2(50) NOT NULL,
  registration_number VARCHAR2(50) NOT NULL,
  active_flag CHAR(1) DEFAULT 'Y' NOT NULL,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT uq_vehicles_vehicle_code
    UNIQUE (vehicle_code),
  CONSTRAINT uq_vehicles_registration_number
    UNIQUE (registration_number),
  CONSTRAINT ck_vehicles_active_flag
    CHECK (active_flag IN ('Y', 'N'))
);
--------------------------------------------------------------------------------
-- gps
--------------------------------------------------------------------------------
CREATE TABLE gps (
  gps_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY
         CONSTRAINT pk_gps PRIMARY KEY,
  source_system VARCHAR2(50) NOT NULL,
  external_event_id VARCHAR2(100) NOT NULL,
  event_timestamp TIMESTAMP NOT NULL,
  driver_id NUMBER NOT NULL,
  vehicle_id NUMBER NOT NULL,
  latitude NUMBER(9,6) NOT NULL,
  longitude NUMBER(9,6) NOT NULL,
  speed_kmh NUMBER(6,2),
  heading_degrees NUMBER(3),
  gps_accuracy_m NUMBER(8,2),
  battery_level_percent NUMBER(5,2),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT fk_gps_driver
    FOREIGN KEY (driver_id)
    REFERENCES drivers (driver_id),
  CONSTRAINT fk_gps_vehicle
    FOREIGN KEY (vehicle_id)
    REFERENCES vehicles (vehicle_id),
  CONSTRAINT uq_gps_source_event
    UNIQUE (source_system, external_event_id),
  CONSTRAINT ck_gps_latitude
    CHECK (latitude BETWEEN -90 AND 90),
  CONSTRAINT ck_gps_longitude
    CHECK (longitude BETWEEN -180 AND 180),
  CONSTRAINT ck_gps_speed
    CHECK (speed_kmh IS NULL OR speed_kmh >= 0),
  CONSTRAINT ck_gps_heading
    CHECK (heading_degrees IS NULL OR heading_degrees BETWEEN 0 AND 359),
  CONSTRAINT ck_gps_accuracy
    CHECK (gps_accuracy_m IS NULL OR gps_accuracy_m >= 0),
  CONSTRAINT ck_gps_battery
    CHECK (
      battery_level_percent IS NULL
      OR battery_level_percent BETWEEN 0 AND 100
    )
);
--------------------------------------------------------------------------------
-- Indexes
--------------------------------------------------------------------------------
CREATE INDEX ix_gps_event_timestamp
  ON gps (event_timestamp);
CREATE INDEX ix_gps_driver_timestamp
  ON gps (driver_id, event_timestamp);
CREATE INDEX ix_gps_vehicle_timestamp
  ON gps (vehicle_id, event_timestamp);
CREATE INDEX ix_gps_source_system
  ON gps (source_system);
--------------------------------------------------------------------------------
-- Completion message
--------------------------------------------------------------------------------
BEGIN
  DBMS_OUTPUT.PUT_LINE('Schema created successfully.');
  DBMS_OUTPUT.PUT_LINE('Tables created: drivers, vehicles, gps');
END;
/